-- Sample Products
INSERT INTO products (id, name, description, overview, category_id, subcategory_id, image, images, features, applications, specifications, data_sheet, catalog_files, price, is_warrantied, has_free_shipping, is_featured, is_active, display_order, meta_title, meta_description, created_at, updated_at) VALUES
('magnetik-karistirici-ms300', 'MS-300 Manyetik Karıştırıcı', 
'Yüksek performanslı laboratuvar manyetik karıştırıcısı', 
'MS-300 modeli, güvenilir karıştırma performansı sunan profesyonel laboratuvar ekipmanıdır. Ayarlanabilir hız kontrolü ve ısıtma özelliği ile çeşitli laboratuvar uygulamalarında kullanılabilir.', 
'lab-equipment', 'genel-lab', 
'/images/products/ms300-main.jpg',
'["/images/products/ms300-main.jpg", "/images/products/ms300-side.jpg", "/images/products/ms300-detail.jpg"]',
'["Ayarlanabilir hız kontrolü", "Dijital sıcaklık göstergesi", "Güvenlik uyarı sistemi", "Korozyon dirençli gövde", "Sessiz çalışma"]',
'["Kimyasal analiz", "Biyoloji araştırmaları", "Kalite kontrol", "R&D çalışmaları", "Eğitim laboratuvarları"]',
'{"Hız Aralığı": "100-1500 rpm", "Sıcaklık Aralığı": "Oda sıcaklığı - 300°C", "Karıştırma Kapasitesi": "3000 ml", "Güç Tüketimi": "550W", "Boyutlar": "200x280x120 mm", "Ağırlık": "2.8 kg"}',
'/files/datasheets/ms300-datasheet.pdf',
'["/files/catalogs/magnetic-stirrers-catalog.pdf"]',
'Fiyat için iletişime geçiniz',
1, 1, 1, 1, 1,
'MS-300 Manyetik Karıştırıcı - Protek Analitik',
'Yüksek performanslı MS-300 manyetik karıştırıcı. Ayarlanabilir hız, ısıtma özelliği ve güvenlik sistemleri ile profesyonel laboratuvar uygulamaları için ideal.',
datetime('now'), datetime('now')),

('ph-metre-ph500', 'PH-500 Dijital pH Metre', 
'Yüksek hassasiyetli dijital pH ölçüm cihazı', 
'PH-500 modeli, ±0.01 pH hassasiyetiyle profesyonel pH ölçümü sağlayan dijital pH metredir. Otomatik kalibrasyon ve sıcaklık kompenzasyonu özellikleri ile güvenilir sonuçlar verir.', 
'lab-equipment', 'kimyasal-analiz', 
'/images/products/ph500-main.jpg',
'["/images/products/ph500-main.jpg", "/images/products/ph500-probe.jpg", "/images/products/ph500-display.jpg"]',
'["±0.01 pH hassasiyeti", "Otomatik kalibrasyon", "Sıcaklık kompenzasyonu", "Su geçirmez tasarım", "Data logger özelliği"]',
'["Su analizi", "Gıda kontrolü", "Tarım uygulamaları", "Havuz bakımı", "Endüstriyel prosesler"]',
'{"Ölçüm Aralığı": "0.00-14.00 pH", "Hassasiyet": "±0.01 pH", "Sıcaklık Aralığı": "0-100°C", "Kalibrasyon": "1, 2 veya 3 nokta", "Ekran": "LCD, arka ışıklı", "Pil Ömrü": "1000 saat", "Boyutlar": "180x83x40 mm"}',
'/files/datasheets/ph500-datasheet.pdf',
'["/files/catalogs/ph-meters-catalog.pdf"]',
'Fiyat için iletişime geçiniz',
1, 1, 0, 1, 2,
'PH-500 Dijital pH Metre - Protek Analitik',
'Yüksek hassasiyetli PH-500 dijital pH metre. ±0.01 pH hassasiyetiyle profesyonel ölçüm, otomatik kalibrasyon ve sıcaklık kompenzasyonu özellikleri.',
datetime('now'), datetime('now'));
